### ISSUE TITLE
Does not work with typescript 5.6

### ISSUE THREAD

**Issue by X-Y** [hediet/vscode-debug-visualizer#231]
Hi,
I've been evaluating the plugin with a bare bone ts + vitest setting, and realized that the current version does not work with typescript 5.6

Tested with 5.5.4 and everything works as intended.

When tested with 5.6.2, the following text shows up when I attempt to visualize an array:

this.tsApi.isNode is not a function
